application: savvychat
version: 1
runtime: python
api_version: 1

inbound_services:
- channel_presence

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /icons
  static_dir: icons

- url: /jquery-1.9.1.min.js
  static_files: jquery-1.9.1.min.js
  upload: jquery-1.9.1.min.js

- url: /sounds
  static_dir: sounds
  
- url: /todo.txt
  static_files: todo.txt
  upload: todo.txt

- url: /.*
  script: savvychat.py
