application: savvychat
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /icons
  static_dir: icons

- url: /json2.js
  static_files: json2.js
  upload: json2.js

- url: /sounds
  static_dir: sounds
  
- url: /help.htm
  static_files: help.htm
  upload: help.htm
  
- url: /gadget.xml
  static_files: gadget.xml
  upload: gadget.xml
  
- url: /todo.txt
  static_files: todo.txt
  upload: todo.txt

- url: /.*
  script: savvychat.py